version: "3.9"

services:
  database_postgres:
    image: postgres
    container_name: database_pg
    restart: always
    ports:
      - 5432:5432
    # environment:
      # - POSTGRES_USER==${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
    networks:
      - network-cherry-go-local

  database_mongo:
    image: mongo
    container_name: database_mongo
    ports:
      - 27017:27017
    volumes:
      - pgmongo:/data/mongo
    networks:
      - network-cherry-go-local

  database_redis:
    image: redis:alpine
    container_name: database_redis
    ports:
      - 6379:6379
    volumes:
      - pgredis:/data/redis
    networks:
      - network-cherry-go-local

volumes:
  pgdata:
    driver: local
  pgredis:
    driver: local
  pgmongo:
    driver: local

networks:
  network-cherry-go-local:
      driver: bridge
